<?php
/*
Plugin Name: Blood Bowl League Manager Widgits
Plugin URI: http://www.hdwsbbl.co.uk/
Description: All the widgets generated by the BBLM system (Defunct)
Author: Blacksnotling
Version: 1.7
Author URI: https://github.com/blacksnotling
Requires at least: 4.7
Tested up to: 4.9.8

Text Domain: bblm_Widget

*/

/*
*	Filename: bb.widgit.core.php
*	Description: File contains all the widgits related to the BBLM (not theme specific).
*/

/**
 * Obsolete as of BBLM 1.7.
 * This file will be deeleted in the future
 */
